packages/web-fragments/src/gateway/pagesMiddleware.ts

This PR fixes an issue with the gateway Pages middleware where we weren't forwarding all request properties to the upstream (e.g. method, body). Since upstream fragments may be running backend-for-frontend servers, this is a problem since all forwarded requests were coming through as GETs and missing their bodies, etc.

fix: proxy all request properties to upstream

---

e2e/qwik-app/package.json
e2e/qwik-app/vite.config.ts
e2e/remix-app/package.json
e2e/remix-app/vite.config.ts
e2e/simple-spa/vite.config.ts
package.json
packages/reframed/package.json
packages/web-fragments/package.json
packages/web-fragments/vite.config.ts
pnpm-lock.yaml

This PR bundles a few infra-related cleanup tasks:
- move dist entrypoints into `publishConfig`, set default entrypoints to src
- this will allow vite to resolve directly to source when developing locally instead of needing to build and watch all packages beforehand
- replace `__dirname` with `import.meta.url` in es modules
- add missing `reframed` dependency declaration to packages
- I also removed any vite aliases that were aliasing `reframed` now that we are resolving to source from the workspace
- Update `pnpm-lock.yaml` to `lockfileVersion 9.0`
- I also added a (strictly-enforced) `engines` entry to ensure we stay in sync on lockfile format

Infra cleanup

---

packages/reframed/src/reframed.ts

This PR adds a no-op setter to all of the patched `History` methods.
[QwikCity currently tries to wrap these methods](https://github.com/QwikDev/qwik/blob/3c5e5a7614c3f64cbf89f1304dd59609053eddf0/packages/qwik-city/runtime/src/spa-init.ts#L127-L135), which results in a runtime error due to a missing setter.
In the future we should come up with a better workaround that preserves what Qwik is expecting to do.

fix(reframed): add no-op setter on patched History methods

---

e2e/pierced-react/README.md
e2e/pierced-react/package.json
e2e/pierced-react/vite.config.ts
packages/web-fragments/package.json
packages/web-fragments/src/gateway/pagesMiddleware.ts

As per the README changes as you can see I've changed the `pierced-react` dx so that you only need to run the `dev` script and nothing else 😃 
what's cool, is that if you make changes in either the app itself` the fragment elements entrypoint or the fragment gateway one, all gets reflected right away 😄 (but you do need to manually refresh the browser)
(the remix fragment does not reload on changes...)
(things might not be 100% perfect, but I think that it's much better than how it was before 😄) 
__
> [!NOTE]
> The CI failure is unrelated, I am addressing that here: https://github.com/web-fragments/web-fragments/pull/14
> (ideally we should merge #14 before merging this 🙂)

improve pierced-react dev mode plus apply other fixes/improvements

---

e2e/pierced-react-remix-fragment/app/root.tsx
e2e/pierced-react-remix-fragment/app/routes/_index.tsx
e2e/pierced-react/functions/_middleware.ts
e2e/pierced-react/src/App.css
e2e/pierced-react/src/App.tsx
packages/reframed/src/reframed.ts

- use `iframe.contentDocument` instead of main `document` when passing a node as the `scriptLoadingDocument` in writable-dom
- update E2E demos to show reframe with fetch and from target working

Fix reframed script loading document

---

.github/workflows/release.yml

I think that the release workflow requires write permissions to succeed: https://github.com/web-fragments/web-fragments/actions/runs/9943889963/job/27468690963#step:6:39
Note: I'm adding this to the yaml file as I don't seem to be able to globally set workflow permissions:

chore: give contents write permission to release workflow

---

.changeset/strange-candles-fail.md
packages/web-fragments/src/elements/fragment-host.ts

This PR prevents a FOUC when piercing a fragment-host into a fragment-outlet.
When the fragment-host is removed from the DOM and reinserted, its existing stylesheets are destroyed and reloaded, which results in a flash-of-unstyled-content while the styles are being refetched. We now preserve these existing styles by cloning them into new constructable stylesheets and assigning them to `ShadowRoot.adoptedStyleSheets` before reparenting the fragment-host.

fix: prevent piercing FOUC

---

.changeset/silver-swans-jog.md
e2e/pierced-react/functions/_middleware.ts
packages/web-fragments/src/gateway/fragment-gateway.ts
packages/web-fragments/src/gateway/middlewares/cloudflare-pages.ts

For scenarios where you want to completely override the response when an SSR fetch for a fragment fails, we need to add an additional flag that's returned by the onSSRFetchError callback so that the Pages middleware can either return the response or embed it in the initial request to the origin.

feat: extend onSSRFetchError to support overriding the entire response

---

.changeset/brown-lies-divide.md
.changeset/cuddly-shrimps-fly.md
.changeset/tidy-paws-develop.md
e2e/pierced-react/fragments/qwik/src/routes/qwik-page/index.tsx
e2e/qwik-app/package.json
e2e/qwik-app/src/routes/index.tsx
packages/reframed/src/reframed.ts
packages/web-fragments/src/elements/fragment-host.ts
packages/web-fragments/src/elements/fragment-outlet.ts

This PR fixes the server side piercing not triggering qwik fragment's `useVisibleTask$` calls
it does so by: 
- patching the iframe's document `readyState`
- pathing the iframe's `IntersectionObserver`
it also:
- removes the `fragmet-outlet` dispatching of a `qinit` event, since I don't think that that is actually needed
(we can re-introduce it later if need be)

Improvements to make sure that qwik's `useVisibleTask$` can successfully fire

---

packages/web-fragments/package.json
packages/web-fragments/src/elements/tsconfig.json
packages/web-fragments/src/gateway/middlewares/cloudflare-pages/index.ts
packages/web-fragments/src/gateway/middlewares/cloudflare-pages/tsconfig.json
packages/web-fragments/src/gateway/middlewares/tsconfig.cloudflare.json
packages/web-fragments/src/gateway/tsconfig.json
packages/web-fragments/tsconfig.base.json
packages/web-fragments/tsconfig.json
packages/web-fragments/vite.config.ts
pnpm-lock.yaml

This PR sets up multiple tsconfig files for each subproject of the `web-fragments` package.
Since we publish multiple entrypoints from this package (and these entrypoints largely are intended to run in separate environments) we need separate TypeScript configurations for each. Without separate configurations, types intended for one environment will leak into subprojects and conflict with types of another subproject's environment (as we ran into in https://github.com/web-fragments/web-fragments/actions/runs/10013949771/job/27682627734?pr=37).
This PR also removes the vite plugin we were using to generate TypeScript declaration files in favor of using `tsc`. It didn't seem like the vite plugin supported building multiple tsconfig projects, but I could be mistaken. It's also possible that we …

chore: set up separate tsconfigs for web-fragments package

---

.changeset/six-beds-check.md
packages/reframed/src/reframed.ts

This PR fixes an issue where scripts inserted into the main document by code running in the reframed context were being executed in the main context (escaping the reframed sandbox).
We now patch any DOM insertion methods that have to potential to result in script execution to insert script elements into the reframed document instead. By executing scripts in the reframed context first, we don't need to try to make them inert in other ways (e.g. changing the `type` attribute) before inserting them into the main document. We can take advantage of scripts having exactly-once execution semantics.
Scripts have an internal `already started` flag that keeps track of whether they've been executed, and this flag is copied when cloning the element. Our approach is to clone the script, execute the …

Patch DOM insertion methods to execute inserted scripts in reframed context

---

.changeset/moody-lies-remain.md
e2e/pierced-react/src/index.css
e2e/pierced-react/src/init.ts
e2e/pierced-react/src/routes/root.tsx
packages/web-fragments/src/elements/fragment-host.ts

Prevents style leakage by setting all css properties to `initial` by default. This prevents scenarios where `some-attribute: inherit` is causing styles from the legacy host application to leak into fragments.

feat: Prevent styling leakage from inherited css properties

---

.changeset/beige-suits-yawn.md
packages/web-fragments/src/elements/fragment-host.ts

This PR preserves focus and selection state when we pierce an existing `<fragment-host>` into a `<fragment-outlet>`.
Selection state restoration is only a best-effort attempt due to lacking browser support and unspecified behavior in some situations. Namely, [`ShadowRoot.getSelection()`](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot) is non-standard and currently only supported in Chromium browsers. Browser behavior is also unspecified when returning selection ranges that span across shadow root boundaries. In the future, we can take advantage of [`Selection.getComposedRanges()`](https://developer.mozilla.org/en-US/docs/Web/API/Selection/getComposedRanges) to help with this once it has broader browser support.

fix: Preserve focus and selection state when piercing

---

.changeset/smart-rocks-tease.md
e2e/pierced-react/fragments/remix/app/routes/remix-page_.details.tsx
packages/reframed/package.json
packages/reframed/src/reframed.ts

Our previous assumptions in [#42](https://github.com/web-fragments/web-fragments/pull/42) turned out to be wrong. We do indeed need to patch the main execution context's insertion methods. We now patch them to check if the node the insertion method is being called on is within a reframed container, and if so execute any potential script elements within the associated reframed context.

fix: DOM insertion method patching v2

---

.changeset/chilled-ways-swim.md
.changeset/happy-goats-clap.md
.changeset/pretty-forks-switch.md
.changeset/smart-rocks-tease.md
packages/reframed/package.json
packages/reframed/src/reframed.ts
packages/web-fragments/src/elements/fragment-host.ts

This PR refactors how we patch the main execution context. We now make these patches in dedicated methods rather than within `monkeyPatchIframeDocument()` (which is really focused on patching the iframe's execution context, not the parent document). This initialization now happens in an idempotent way when `reframed()` is called.
It also refactors how we attach and clean up the navigation event listeners we add to the parent window. These listeners are now removed automatically when the iframe's window `unload` event fires, relieving the caller of `reframed` from the burden of needing to invoke a cleanup function.

Refactor History API patches and global event listener cleanup

---

.changeset/friendly-coins-mate.md
.changeset/rich-days-carry.md
.changeset/shaggy-birds-worry.md
packages/reframed/src/reframed.ts

This PR refactors our approach to patching the iframe in `reframed`. 
This includes:
- introducing a new mechanism for referencing some of the original unpatched properties internally where necessary
- fixing an incorrect property definition: 
```diff
- document.stylesheets
+ document.styleSheets
```
- removing internal references to `document.unreframedBody` in preparation for its deprecation and removal
- renaming `monkeyPatchIframeDocument()` to `monkeyPatchIframeEnvironment()` since it also patches properties on `iframeWindow`
- moving navigation handlers into `monkeyPatchIframeEnvironment()`
- refactoring `addEventListener()`/`removeEventListener()` patches at the `Window`/`Document` level into a single proxy at the `EventTarget` level that properly handles redirecting and cleanup. …

Refactor iframe and event listener patching

---

.changeset/yellow-tools-beam.md
e2e/pierced-react/fragments/remix/app/root.tsx
packages/reframed/src/reframed.ts
packages/web-fragments/src/elements/fragment-host.ts
packages/web-fragments/src/gateway/middlewares/cloudflare-pages/index.ts

This adds a new header to requests sent to the fragment upstream that will help us reliably identify when the fragment is being run in standalone mode vs embedded mode.

feat: Add a header to signal when fragments are running in embedded mode

---

e2e/pierced-react/fragments/qwik/src/entry.ssr.tsx

This PR updates the example app's qwik fragment to:
- make the `q:base` root-relative. Assets weren't being loaded from the correct path because they were being fetched relative to the current page URL of `/qwik-page/`.
- override `serverData.url` to match that of the parent application's origin. Qwik has some same-origin checks to determine how it should handle navigations and the mismatch was causing all navigations to be hard navigations.

chore: [qwik] make `base` root-relative; override server URL

---

.github/workflows/playwright-reframed.yml
packages/reframed/.gitignore
packages/reframed/package.json
packages/reframed/playwright.config.ts
packages/reframed/tests/basic.spec.ts
packages/reframed/tests/index.ts
packages/reframed/vite.config.ts
pnpm-lock.yaml

This PR sets up playwright testing for `reframed` along with a basic test suite.
It adds a playwright GitHub Actions workflow to run these tests on PRs and pushes that include changes to files within the `packages/reframed` directory.

Set up playwright testing for reframed

---

.changeset/gentle-timers-bow.md
.changeset/nine-melons-admire.md
packages/reframed/src/reframed.ts
packages/reframed/tests/history.spec.ts

This PR fixes an issue with client-side navigation initiated in a reframed context resulting in more `popstate` events being dispatched than intended.
We're currently using a synthetic `popstate` event as a way to alert execution contexts of a client-side location change via a series of patches both on the parent window's `history` methods as well as those of the `history` instances inside reframed contexts. What this PR changes is that we now bail out of dispatching that synthetic `popstate` to the reframed context which initiated the navigation.
Why use a synthetic `popstate` event? Client-side routers typically add event listeners for the `popstate` event to trigger a re-render or navigation in response to (for example) the user pressing the back button, so it's the best way we …

Fix double `popstate` on reframed client-side navigations

---

.changeset/quick-buttons-hear.md
.changeset/silly-ways-marry.md
.changeset/sweet-yaks-think.md
packages/web-fragments/src/elements/fragment-host.ts
packages/web-fragments/src/gateway/middlewares/cloudflare-pages/index.ts

This PR fixes a few loose ends around fragment piercing: Previously...
- the Cloudflare Pages middleware wasn't including the `fragment-id` on the `<fragment-host>` element it SSRs
- `<fragment-host>`s would indiscriminately pierce into any `<fragment-outlet>` rather than making sure it has a matching `fragment-id` first
- multiple `<fragment-host>`s could potentially attempt to pierce into a single `<fragment-outlet>`
Now, we include the `fragment-id` from the SSR response, and `<fragment-host>`s make sure they're piercing into a matching `<fragment-outlet>` and that nobody else has already done so.

Pierce `<fragment-host>` s only into matching `<fragment-outlet>`s

---

.changeset/warm-knives-talk.md
packages/reframed/src/reframed.ts
packages/reframed/tests/basic.spec.ts

Fixes #68 
Patches [window.innerWidth](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth), `innerHeight`, `outerWidth`, and `outerHeight` to read from the parent frame, since the iframe is hidden and its dimensions are 0x0.
Alternatively, we might want the patch to read the ShadowRoot's firstElementChild's dimensions? That won't have the inner/outer distinction available.

Add window size patches

---

.changeset/little-walls-hear.md
packages/reframed/src/reframed.ts
packages/reframed/tests/basic.spec.ts

This PR allows custom elements to be created using the reframed document instead of redirecting to the main document. This enables reframed contexts to make use of their own custom element registries.
Note that this fix only affects custom elements created from within a reframed context. Any custom elements included in an embedded fragment during the initial SSR response will be parsed into the main document and will still use the top-level custom element registry. We'll need more work to support custom elements for that scenario.
Refs #72

Create custom elements using the reframed document

---

.changeset/late-turtles-flow.md
.changeset/silver-fans-draw.md
packages/web-fragments/src/elements/fragment-host.ts
packages/web-fragments/src/elements/fragment-outlet.ts
packages/web-fragments/src/gateway/middlewares/cloudflare-pages/index.ts

- fix fragment-host not piercing into fragment-outlet
- fix CSS stylesheets not inserting rules in correct order

fix: fix fragment-host piercing and CSS specificity when piercing

---

.changeset/brave-cooks-jog.md
.changeset/itchy-goats-cough.md
.changeset/pink-rings-change.md
packages/reframed/src/reframed.ts

This PR moves patches of the reframed document to the `document` instance itself rather than `Document.prototype`. It also fixes the patches for `document.getElementsBy*()` to redirect to the shadow root's first element child rather than the shadow root itself (which doesn't have those methods on its interface). It also removes the `document.unreframedBody` property we're no longer depending on externally.
Fixes #60 #73

Patch `document` instead of `Document.prototype`

---

.changeset/popular-paws-cheer.md
.changeset/proud-glasses-hear.md
packages/web-fragments/src/gateway/middlewares/cloudflare-pages/index.ts

This PR introduces an `additionalHeaders` option to the Cloudflare Pages middleware to allow including additional headers when forwarding requests to fragment upstreams.
This will enable use-cases such as resolving a user's locale preference within the Fragment Gateway and passing that along to the upstream fragment application via an `Accept-Language` header.

Add `additionalHeaders` option to Cloudflare Pages middleware

---

.changeset/gorgeous-owls-kneel.md
packages/web-fragments/src/elements/fragment-host.ts

This PR fixes #78, where a fragment containing CSS that includes `@import` directives would cause a runtime error during fragment piercing.
`@import` directives are currently not allowed inside of Constructed Stylesheets, so we need to skip over them when copying over style rules to the constructed stylesheet we use to avoid FOUC when reparenting the `<fragment-host>` into the `<fragment-outlet>`.

Skip inserting CSS rules containing `@import` directives when piercing

---

.changeset/sweet-goats-work.md
packages/web-fragments/src/gateway/middlewares/cloudflare-pages/index.ts

This PR refactors the Cloudflare Pages fragment gateway middleware to consolidate the fetching logic and be easier to follow.
In some respects, this is also a followup to https://github.com/web-fragments/web-fragments/pull/87 to fix an issue where `additionalHeaders` weren't being included for non-document requests. Core fragment-fetching logic is now encapsulated in a `fetchFragment` function that's used in all scenarios when making upstream fetches to a fragment.

Refactor Cloudflare Pages middleware

---

.changeset/plenty-dragons-repeat.md
.gitignore
packages/web-fragments/package.json
packages/web-fragments/src/gateway/middlewares/cloudflare-pages/index.ts
packages/web-fragments/src/gateway/stream-utilities.ts
pnpm-lock.yaml

This PR utilizes HTMLRewriter's support for interpolating content from a  ReadableStream into HTML transformations. Previously we were limited to injecting content from the upstream only as a string, meaning we had to await the response and block TTFB. Instead, we now pass along the response body stream and it get consumed directly as part of the HTML transformation.
This PR adds a new `asReadableStream` tagged template helper to produce a `ReadableStream` from interpolated strings and/or other `ReadableStream`s in a nice ergonomic way. e.g.
```tsx
const fragmentTemplateStream = asReadableStream`
<template>${upstreamResponse.body}</template>
`
```

Embed fragment HTML via ReadableStream

---

.changeset/config.json
.changeset/fifty-owls-exist.md
packages/web-fragments/CHANGELOG.md

It looks like the CHANGELOG for the `web-fragments` package was manually edited instead of being updated via changesets during a release. This PR removes the manual entry and adds a corresponding changeset for the change.
This PR also updates the changelog generator to [`@changesets/changelog-github`](https://github.com/changesets/changesets/tree/main/packages/changelog-github) for nicer formatting, including commit/PR links and contributor mentions.

Fix changesets

---

.changeset/gorgeous-olives-wink.md
packages/web-fragments/src/gateway/fragment-gateway.ts

The property `upstream` was renamed to `endpoint` in #94 and retroactively marked as `@deprecated`, but it's still a required property of `FragmentConfig` so TypeScript gets mad if it's not provided. This PR makes this property optional.

Make deprecated property `upstream` optional

---

packages/reframed/package.json
packages/web-fragments/package.json
pnpm-lock.yaml
pnpm-workspace.yaml

This just simplifies dependency management across various parts of the monorepo.
This is in prep PR for the test suite PR.

build: introduce pnpm catalog for sharing of common npm dependencies

---

.changeset/silver-lemons-sniff.md
packages/reframed/src/reframed.ts

Previously before we used shadowRoot the active element in the fragment targeted main document's active element, but now that we require the use of shadowRoot, we must use shadowRoot.activeElement instead because otherwise activeElement is set to the element that owns the fragment's shadowroot. This causes the code in fragment to escape the shadowroot, which results in weird bugs.

fix(reframed): document.activeElement should always point to shadowRoot.activeElement

---

.changeset/great-carrots-protect.md
packages/reframed/src/reframed.ts

Previously we accidentally treated them as inline scripts that haven't been fully parsed and appended, which caused double execution of these scripts.
This issue prevented Analog from bootstrapping correctly in reframed context.

fix(reframed): correctly execute external scripts (with src)

---

.changeset/sixty-phones-notice.md
.changeset/swift-turtles-nail.md
packages/reframed/src/reframed.ts

Any node within the fragment's shadowRoot should consider its ownerDocument to be the shadowRoot.
If we don't patch this, it's too easy for code to escape the shadowRoot boundary when traversing the DOM.

fix(reframed): node.ownerDocument should return return the fragment's shadowRoot

---

packages/reframed/vite.config.ts

It seems that the recent vite introduced in bab0a9d changed the behavior and the built has been failing since.

build: fix reframed's vite config

---

.changeset/modern-poets-rhyme.md
packages/reframed/src/reframed.ts

We need to read it from the main window.

fix(reframed): correctly support window.visualViewport

---

.changeset/great-doors-type.md
packages/web-fragments/src/gateway/middleware/web.ts
packages/web-fragments/test/gateway/gateway.spec.ts

The gateway now rewrites fragment html so that any `<html>`, `<head>`, and `<body>` tags are replaced with `<wf-html>`, `<wf-head>`, and `<wf-body>` tags.
DOM doesn't allow multiple of these three elements in the document, and the main document already contains them.
We need to replace these tags, to prevent the DOM from silently dropping them when the content is added to the main document.

fix(gateway): prefix <html>, <head>, and <body> tags in fragment response as <wf-html>, <wf-head>, and <wf-body>

---

packages/web-fragments/test/playground/vite.config.ts

We need to better identify fragment requests coming from the browser and process them via the gateway, otherwise the fragment responses don't get rewritten by the middleware.

dev: fix routing issue in playground vite middleware config

---

.changeset/empty-colts-decide.md
.github/workflows/gateway-tests.yml
packages/web-fragments/src/gateway/middleware/web-to-node-adapter.ts

This is mainly to make it easier to use the gateway in wider range of environments.

fix(gateway): make gateway compatible with node 20

---

.changeset/tender-rings-impress.md
.github/workflows/playwright-web-fragments.yml
.github/workflows/vitest-web-fragments.yml
packages/web-fragments/package.json
packages/web-fragments/src/elements/reframed/reframed.ts
packages/web-fragments/src/elements/utils/selector-helpers.spec.ts
packages/web-fragments/src/elements/utils/selector-helpers.ts
packages/web-fragments/test/gateway/package.json
packages/web-fragments/test/playground/dom-querying/fragment.html
packages/web-fragments/test/playground/dom-querying/index.html
packages/web-fragments/test/playground/dom-querying/spec.ts
packages/web-fragments/test/playground/index.html
pnpm-lock.yaml
pnpm-workspace.yaml

CSS selectors used in `querySelector` and `querySelectorAll` are patched to replace html, head, and body tags with their wf-* custom element counterpart.
`document.documentElement`, `document.body`, and `document.head` are also patched to return references to valid elements. These references are cached when a valid element is found in order to reduce lookup time.

fix(reframed): rewrite queries for html,head,body to target wf-* custom elements

---

.changeset/fluffy-guests-burn.md
.changeset/strange-games-lie.md
e2e/node-servers/CHANGELOG.md
e2e/node-servers/app/client/CHANGELOG.md

these were created accidentaly or are leftovers from having reframed library in the repo

dev: remove obsolete changelog entries

---

.changeset/slow-kings-hope.md
packages/web-fragments/src/elements/reframed/reframed.ts
packages/web-fragments/test/playground/location-and-history/fragment.html
packages/web-fragments/test/playground/location-and-history/index.html
packages/web-fragments/test/playground/location-and-history/spec.ts
packages/web-fragments/test/playground/location-and-history/unbound.html

Previously a hard navigation (`location.href = '/new-url'`) or location reload (`location.reload()`) within a (bound) fragment would result in this fragment getting into a broken state.
The root cause was that navigation would cause the reframed iframe reloaded, unloading all JS code but the DOM remained unchanged.
This resulted in broken UX.
With this change any hard navigation or reload within a bound fragment will be propagated to the main window, causing a hard navigation or reload in the app shell.
It's a bit unclear what should happen when this kind of navigation happens in an unbound fragment. For this reasons, we only empty the fragment DOM for now and log a warning.
This PR is a different take on #112 (the main difference being that we detect the reload much earlier and prevent …

fix: correctly handle hard navigations and reloads from fragments

---

packages/web-fragments/package.json

This PR fixes the path to the node middleware type declaration

fix: fix types path for node middleware

---

packages/web-fragments/package.json
packages/web-fragments/vite.config.ts
pnpm-lock.yaml

Previously, we accidentally bundled the htmlrewriter package into web-fragments repo.
Bundling the package in prevented the htmlrewriter resolutions to be honored within the client application.
See:
- https://github.com/anfibiacreativa/htmlrewriter/blob/fix-emoji-crash/package.json#L22
- https://github.com/anfibiacreativa/htmlrewriter/blob/fix-emoji-crash/cloudflare.js
Additionally by depending on the github fork we made it impossible to install the package in yarn v2 which has bugs in implementation of its github protocol.
This pr switches us over to temporarily published wf-htmlrewriter instead.

fix: make htmlrewriter an external dependency

---

.changeset/dull-jars-hunt.md
packages/web-fragments/src/gateway/middleware/web-to-node-adapter.ts
packages/web-fragments/src/gateway/middleware/web.ts
packages/web-fragments/test/gateway/gateway.spec.ts

When piercing, we always need the fragment to return a response body.
For this reason we must disable conditional http requests when piercing by not relaying if-none-match and if-modified-since headers to the fragment endpoint.
This change also contains a small change to the node adapter, so that it doesn't crash when it encounters a 304 response from the shell.

fix(gateway): disable conditional http requests when fetching a fragment to pierce

---

.changeset/honest-buckets-design.md
packages/web-fragments/src/gateway/middleware/web.ts
packages/web-fragments/test/gateway/gateway.spec.ts

Nested doctype tags might cause some browsers to complain or choke (e.g. Firefox in some cases).
Browsers don't materialize this tag in the DOM anyway so it should be ok to strip them (if it's nested within other elements).

fix(gateway): strip <!doctype> tags from fragment responses

---

.changeset/pretty-doors-guess.md
e2e/node-servers/app/server/src/connect.ts
e2e/node-servers/app/server/src/express.ts
e2e/pierced-react/functions/_middleware.ts
packages/web-fragments/src/gateway/fragment-gateway.ts
packages/web-fragments/src/gateway/middleware/readme.md
packages/web-fragments/src/gateway/middleware/web.ts
packages/web-fragments/test/gateway/gateway.spec.ts

These APIs were originally misnamed, so this change corrects it.
Piercing is the process of inserting a fragment into the initial payload, and there isn´t such thing as "prepiercing" stage in the fragment´s lifecycle.
The change was made a backwards compatible way.

feat: replace prePiercingStyles and prePiercingClassNames with piercing* names

---

packages/web-fragments/package.json
packages/web-fragments/test/gateway/package.json

Previously the setup.ts script didn't run which caused runtime errors when test-debug:gateway was started.

dev: fix pnpm test-debug:gateway script

---

.changeset/tidy-feet-learn.md
packages/web-fragments/src/elements/reframed/script-execution.ts
packages/web-fragments/test/playground/index.html
packages/web-fragments/test/playground/script-insertion/index.html
packages/web-fragments/test/playground/script-insertion/spec.ts

Script tags that have already been evaluated and added to the iframe document should not be re-evaluated when a reference to that node is then added to the DOM via another script tag.
Consider this scenario in the fragment application:
Because the `<script id="counter-script" />` element has already been "evaluated" in the iframe document, calling `document.body.appendChild()` on the inert script should be a noop. However, reframed incorrectly adds this script to the iframe (again) because the reference to the inert script in the reframedDOM was never truly evaluated in the reframedDOM.
```
[ ] Yes
[x] No
```

fix (reframed): fix inert scripts being incorrectly evaluated on insertion

---

.changeset/olive-toys-doubt.md
.changeset/violet-dogs-tie.md
packages/web-fragments/src/elements/reframed/script-execution.ts
packages/web-fragments/src/gateway/fragment-gateway.spec.ts
packages/web-fragments/src/gateway/fragment-gateway.ts
packages/web-fragments/src/gateway/middleware/web.ts
packages/web-fragments/test/playground/script-insertion/index.html

Sometimes, fragments are hosted on the same root pathname but can be differentiated by specific search param patterns. For example, `react-router` makes requests to `/__manifest?p=/path/to/route`. Currently, the gateway has no mechanism for matching against a search parameter pattern, only a pathname.
This PR adds search param matching as a non-breaking change by using `path-to-regexp` to support the same matching syntax used for pathname matching.
```
[ ] Yes
[x] No
```

fix (gateway): add support for search params match

---

.changeset/brown-penguins-serve.md
packages/web-fragments/src/gateway/fragment-gateway.ts
packages/web-fragments/src/gateway/middleware/web.ts
packages/web-fragments/test/gateway/gateway.spec.ts

Fragments can now be registered using a url or function that matches the standard Fetch API.
This enables more flexibility when connecting to fragment endpoints. On Cloudflare specifically this means that a gateway can connect to a fragment using a service binding.
```
[ ] Yes
[x] No
```

feat: make it possible to register a fragment endpoint as a fetcher function

---

.changeset/thin-otters-cover.md
packages/web-fragments/src/elements/reframed/iframe-patches.ts
packages/web-fragments/test/playground/reframing/spec.ts

By default they operate on the iframe, which returns non-sense values.
- ...
```
[ ] Yes
[ ] No
```

fix: fix window.matchMedia to operate on the visible window/document

---

.changeset/gentle-houses-rule.md
packages/web-fragments/src/elements/reframed/iframe-patches.ts
packages/web-fragments/test/playground/reframing/spec.ts

Setting document.title should actually update the `<title>` element within the `<head>` of the fragment.
And bound fragments should also update parent's document.title — for bound fragments the title is a shared state, just like window.location and history.

fix: correctly update document.title

---

pnpm-lock.yaml
pnpm-workspace.yaml

This resolves the issue with CI being suddenly broken due to:
SyntaxError: The requested module '@playwright/test' does not provide an export named 'Frame'

dev: update playwright version to 1.54.2

---

.changeset/khaki-apricots-run.md
.changeset/real-sheep-hammer.md
.changeset/tasty-parents-kiss.md
.changeset/tricky-singers-love.md
packages/web-fragments/package.json
packages/web-fragments/src/elements/reframed/reframed.ts
packages/web-fragments/src/elements/reframed/utils/web-fragment-error.ts
packages/web-fragments/src/gateway/fragment-gateway.ts
packages/web-fragments/src/gateway/middleware/web-to-node-adapter.ts
packages/web-fragments/src/gateway/middleware/web.ts
packages/web-fragments/test/gateway/gateway.spec.ts
packages/web-fragments/test/playground/fragment-csp/fragment.html
packages/web-fragments/test/playground/fragment-csp/index.html
packages/web-fragments/test/playground/fragment-csp/spec.ts
packages/web-fragments/test/playground/fragment-infinite-recursion-breaker/index.html
packages/web-fragments/test/playground/fragment-infinite-recursion-breaker/spec.ts
packages/web-fragments/test/playground/fragment-x-frame-options-deny/fragment.html
packages/web-fragments/test/playground/fragment-x-frame-options-deny/index.html
packages/web-fragments/test/playground/fragment-x-frame-options-deny/spec.ts
packages/web-fragments/test/playground/index.html
packages/web-fragments/test/playground/location-and-history/spec.ts
packages/web-fragments/test/playground/playwright.utils.ts
packages/web-fragments/test/playground/public/baz/index.html
packages/web-fragments/test/playground/vite.config.ts

If the fragment gateway was not properly configured (e.g. the routePaths don't contain the main navigable url that starts a fragment), reframed creates an iframe which when loaded by the browser loads the original host html rather than the minimal reframed init html, which then causes a new nested fragment to be created which then repeats the process, resulting in an infinite recursion.
This turns out to be a rather common user error, so to make it easier to diagnose and fix, we now detect it and throw an error.

fix: throw WebFragmentError when we risk infinite iframe recursion during reframe init
